services:
  - type: web
    name: paste-bi
    runtime: node
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ANTHROPIC_API_KEY
        sync: false
